GestaoVendas.Cap03/Controllers/ProdutosController.cs
using GestaoVendas.Cap03.Data;
using GestaoVendas.Cap03.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestaoVendas.Cap03.Controllers
{
    public class ProdutosController : Controller
    {
        // GET: Produtos
        public ActionResult Index()
        {
            return View();
        }

        // GET: Produtos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Produtos/Create
        public ActionResult Incluir()
        {
                ViewBag.ListaDeCategorias = new SelectList(ProdutosDao.ListarCategorias(), "Id", "Descricao");

                return View();
        }

        // POST: Produtos/Incluir
        [HttpPost]
        public ActionResult Incluir(Produto produto, HttpPostedFileBase image)
        {
           
            try
            {

                if (!ModelState.IsValid)//verifica se o estado da pagina é valido
                {
                    return Incluir();
                }
                if (image is null) // verifica se a image for diferente de nulo
                {
                    throw new ArgumentNullException(nameof(image));// se a image nao for carrgada lança um exception
                }

                //se a image diferente de null entao fazer a captura de stream de bytes
                produto.MimeType = image.ContentType;
                       //um tipo           tipo
                byte[] bytes = new byte[image.ContentLength];
                                               // tamanho da imagem/ possa calcular o tamanhoem bites
                image.InputStream.Read(bytes, 0, image.ContentLength);
                //inputStream colocando dentro da VAR bytes[array] a imagem transformando em bytes alocando dentro de "bytes" e o tamanho informado 'contentlenght'

                //armazenar os bytes
                produto.Foto = bytes;

                ProdutosDao.IncluirProduto(produto);

                // TODO: Add insert logic here
                return RedirectToAction("Listar");
            }
            catch
            {
                return View();
            }
        }

        public FileResult BuscarFoto(int id)
        {
            var produto = ProdutosDao.BuscarProduto(id);
            return File(produto.Foto, produto.MimeType);
        }
        public ActionResult Listar()
        {
            return View(ProdutosDao.ListarProdutos());
        }

        // GET: Produtos/Edit/5
        [HttpGet]
        public ActionResult Alterar(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Nenhum código fornecido");
                }
                var produto = ProdutosDao.BuscarProduto((int)id);
                if (produto == null)
                {
                    throw new
                    Exception("Nenhum produto encontrado com este código");
                }
                ViewBag.ListaDeCategorias = new SelectList(ProdutosDao.ListarCategorias(), "Id", "Descricao");
                return View(produto);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("Error");
            }
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        public ActionResult Alterar(Produto produto, HttpPostedFileBase image)
        {
            if (!ModelState.IsValid)
            {
                return Alterar(produto.Id);
            }
            try
            {
                if (image != null)
                {
                    produto.MimeType = image.ContentType;
                    byte[] bytes = new byte[image.ContentLength];
                    image.InputStream.Read(bytes, 0, image.ContentLength);
                    produto.Foto = bytes;
                }
                ProdutosDao.AlterarProduto(produto);
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("Error");
            }
        }
    }

     /*   // GET: Produtos/Delete/5
        public ActionResult Excluir(int id)
        {
            return View();
        }

        // POST: Produtos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }*/
}
   

GestaoVendas.Cap03/Views/Produtos/Alterar.cshtml
@model GestaoVendas.Cap03.Models.Produto

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>


@using (Html.BeginForm("Alterar", "Produtos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Produto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Foto)
    @Html.HiddenFor(model => model.MimeType)

    <div class="form-group">
        @Html.LabelFor(model => model.IdCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdCategoria, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unidade, "", new { @class = "text-danger" })
        </div>
    </div>

    @* <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
           @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("voltar p/ lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestaoVendas.Cap03/Views/Produtos/Incluir.cshtml
@model GestaoVendas.Cap03.Models.Produto

@{
    ViewBag.Title = "Incluir";
}

<h2>Incluir</h2>


@using (Html.BeginForm("Incluir", "Produtos", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Produto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IdCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.IdCategoria, (SelectList)ViewBag.ListaDeCategorias, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
        </div>
    </div>

    @* <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Image" class="form-control" />
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("voltar p/ Lista", "Listar")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestaoVendas.Cap03/Views/Produtos/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Gestão de clientes - Escolha uma opção</h2>
<hr />

    @Html.ActionLink("Incluir novo produto", "Incluir", null,new { @class = "btn btn-primary" })
    @Html.ActionLink("Listar Produtos", "Listar", null, new {@class = "btn btn-warning" })

GestaoVendas.Cap03/Views/Produtos/Listar.cshtml
@model IEnumerable<GestaoVendas.Cap03.Models.Produto>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Novo Produto", "Incluir", null , new {@class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unidade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unidade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            <img src="@Url.Action("BuscarFoto", "Produtos", new { id = item.Id })" style="width:100px;" />
        </td>
        <td>
            @Html.ActionLink("Alterar", "Alterar", new { id=item.Id })
            @Html.ActionLink("Editar", "", new { id=item.Id })
            @Html.ActionLink("Excluir", "#", new { id=item.Id })
        
        </td>
    </tr>
}

</table>