GestaoVendas.Cap03/Controllers/PedidosController.cs
using GestaoVendas.Cap03.Data;
using GestaoVendas.Cap03.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestaoVendas.Cap03.Controllers
{
    public class PedidosController : Controller
    {
        // GET: Pedidos
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Incluir()
        {
            ViewBag.ListaDeClientes = new SelectList(
            ClientesDao.ListarClientes(), "Documento", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(Pedido pedido)        


             
        {
            pedido.Data = DateTime.Now;
            if (!ModelState.IsValid)
            {
                return Incluir();
            }
            try
            {
                PedidosDao.IncluirPedido(pedido);
                ViewBag.ListaDeClientes = new SelectList(
                ClientesDao.ListarClientes(), "Documento", "Nome");

                return Redirect("/Pedidos/Listar?id=" + pedido.DocCliente);
            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                return View("Error");
            }
        }
        public ActionResult Listar(string id)
        {
            try
            {
                ViewBag.ListaDeClientes = new SelectList(
                ClientesDao.ListarClientes(), "Documento", "Nome");
                return View(PedidosDao.ListarPedidos(id));
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("Error");
            }
        }

        // GET: Produtos/Delete/5
        public ActionResult Remover(int id)
        {
            return View(PedidosDao.BuscarPedido(id));
        }

        // POST: Produtos/Delete/5
        [HttpPost]
        public ActionResult Remover(int? id, Pedido collection)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Nenhum código fornecido");
                }
                var pedido = PedidosDao.BuscarPedido((int)id);

                if (pedido == null)
                {
                    throw new
                    Exception("Nenhum pedido encontrado");
                }
                var doc = pedido.DocCliente;

                PedidosDao.RemoverPedido(pedido);

                return Redirect("/Pedidos/Listar?id=" + doc);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }
    }
    }

GestaoVendas.Cap03/Views/Pedidos/Incluir.cshtml
@model GestaoVendas.Cap03.Models.Pedido

@{
    ViewBag.Title = "Incluir";
}

<h2>Incluir</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DocCliente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DocCliente,(SelectList)ViewBag.ListaDeClientes,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocCliente, "",new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroPedido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroPedido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroPedido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Listar")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestaoVendas.Cap03/Views/Pedidos/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Gestão de Pedidos - Selecione uma opção</h2>
<hr />

@Html.ActionLink("Incluir novo pedido", "Incluir")
@Html.ActionLink("Listar pedidos por cliente", "Listar")

GestaoVendas.Cap03/Views/Pedidos/Listar.cshtml
@model IEnumerable<GestaoVendas.Cap03.Models.Pedido>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Novo pedido", "Incluir")
</p>
<h2>Listar Pedidos por Cliente</h2>
@using (Html.BeginForm("Listar", "Pedidos", FormMethod.Post))
{
    <div class="form-horizontal">

        <div class="form-group">
            @Html.Label("Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id",(SelectList)ViewBag.ListaDeClientes, "TODOS",new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar Pedidos"
                       class="btn btn-info" />
            </div>
        </div> 
        <hr />
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DocCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroPedido)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DocCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroPedido)
            </td>
            <td>
                @Html.ActionLink("Incluir Itens", "Incluir", "Itens", new { idPedido = item.Id }, null) |
                @Html.ActionLink("Remover", "Remover", new { id = item.Id })
            </td>
        </tr>
    }
</table>

GestaoVendas.Cap03/Views/Pedidos/Remover.cshtml
@model GestaoVendas.Cap03.Models.Pedido

@{
    ViewBag.Title = "Remover";
}

<h2>Remover</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroPedido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroPedido)
        </dd>

    </dl>

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Listar")
        </div>
    }
</div>